name = "crypto-risk-monitor-cron"
main = "src/worker.js"
compatibility_date = "2026-01-01"

[triggers]
crons = [
  "2,4,22,28,34,52,57,59 * * * *",
  "47 4 * * *",
  "3,6,21,26,31,36,53,58 * * * *",
  "20 22 * * 1-5",
]
